Auto close PR test
appwrite/sdk-for-go pull request #14
Opened 2024-06-26 23:34 UTC by EVDOG4LIFE

## What does this PR do?
This PR adds a GitHub workflow to automatically close pull requests and add a comment explaining that the repository is auto-generated and does not accept direct contributions. This is being tested on an unused SDK repository.

## Test Plan
To verify this change:
1. Create a new pull request in the unused SDK repository.
2. Observe that the workflow is triggered automatically.
3. Verify that a comment is added to the pull request with the specified text.
4. Confirm that the pull request is automatically closed.
5. Test reopening the pull request to ensure the workflow triggers again.

## Related PRs and Issues
N/A - This is a standalone change for repository management.

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
Yea

2024-06-27 00:16 UTC, stnguyen90 requested changes
Left a comment.

2024-06-27 00:16 UTC, stnguyen90 commented on .github/workflows/autoclose.yml
> +              body: 'This library is auto-generated by Appwrite custom [SDK Generator](https://github.com/appwrite/sdk-generator), and does not accept pull requests directly. To learn more about how
```suggestion
              body: 'This library is auto-generated by the Appwrite [SDK Generator](https://github.com/appwrite/sdk-generator), and does not accept pull requests directly. To learn more about how you can help us improve this SDK, please check the [contributing guide](https://github.com/appwrite/sdk-generator/blob/master/CONTRIBUTING.md) before submitting a pull request.'
```

2024-06-27 00:16 UTC, stnguyen90 commented on .github/workflows/autoclose.yml
How do we make sure this only runs for contributors and doesn't run when we need to submit a PR?

2024-06-27 17:45 UTC, EVDOG4LIFE commented on .github/workflows/autoclose.yml
I believe this refactor should correct now

2024-07-02 04:31 UTC, stnguyen90 approved these changes

2024-07-02 04:32 UTC, merged